package:
  name: perl-cairo
  version: "1.107"

source:
  url: https://cpan.metacpan.org/authors/id/X/XA/XAOC/Cairo-1.107.tar.gz
  sha256: 5e1de126ddf93bd5b13f13a52f50d7f7af1157265b7f10e53d585ee1827be169

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
    - perl-extutils-pkgconfig
    - perl-extutils-makemaker
    - perl-extutils-depends
    - cairo
    - pkg-config

  run:
    - perl
    - perl-extutils-pkgconfig
    - perl-extutils-depends
    - cairo
    - xorg-libxrender
    - xorg-libsm
    - xorg-libxext

test:
  commands:
    - perl -e "use Cairo"

about:
  home: http://gtk2-perl.sourceforge.net
  license: lgpl_2_1
  summary: 'Perl interface to the cairo 2d vector graphics library'
