package:
  name: perl-template-toolkit
  version: "2.29"

source:
  url: https://cpan.metacpan.org/authors/id/A/AT/ATOOMIC/Template-Toolkit-2.29.tar.gz
  sha256: 2bddd71cf41fb805fd5234780daf53226b8e7004c623e1647ba2658113614779

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
    - perl-appconfig
    - perl-cgi
    - perl-image-info
    - perl-image-size
    - perl-test-leaktrace

  run:
    - perl
    - perl-appconfig
    - perl-cgi
    - perl-image-info
    - perl-image-size
    - perl-test-leaktrace

test:
  # Perl 'use' tests: relying on "run_test.pl" due to version differences
  # between the top-level and sub- packages.

about:
  home: http://metacpan.org/pod/Template-Toolkit
  license: perl_5
  summary: 'comprehensive template processing system'
