{% set name = "perl-test-class-moose" %}
{% set version = "0.97" %}
{% set sha256 = "a99a6d96569f5ecfb263aaa2bc1ff43324610b545bca8e7c1bd02118fa92c1e2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Test-Class-Moose-0.97.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
    - perl-parallel-forkmanager
    - perl-file-temp
    - perl-test-warnings
    - perl-moosex-getopt
    - perl-carp
    - perl-sub-attribute
    - perl-extutils-makemaker
    - perl-import-into
    - perl-package-deprecationmanager
    - perl-list-someutils
    - perl-lib
    - perl-exporter
    - perl-moose
    - perl-try-tiny
    - perl-namespace-autoclean
    - perl-test-requires
    - perl-module-runtime
    - perl-json-maybexs
    - perl-test-most
    - perl-module-util
    - perl-test-simple

  run:
    - perl
    - perl-namespace-autoclean
    - perl-parallel-forkmanager
    - perl-moosex-getopt
    - perl-carp
    - perl-sub-attribute
    - perl-module-runtime
    - perl-import-into
    - perl-json-maybexs
    - perl-test-most
    - perl-package-deprecationmanager
    - perl-list-someutils
    - perl-module-util
    - perl-exporter
    - perl-moose
    - perl-try-tiny

test:
  imports:
    - Test::Class::Moose

about:
  home: http://metacpan.org/release/Test-Class-Moose/
  license: perl_5
  summary: 'Serious testing for serious Perl'

