# Do not forget to update the version string in the peptide-shaker.py file
{% set version = "1.1.beta" %}
{% set sha256 = "0af2c74f582e6b92f5ae586f31c34785db2f623149433b417932038ec53be9ef" %}

package:
  name: pepgenome
  version: {{ version }}

source:
  url: https://github.com/bigbio/pgatk/releases/download/PepGenome-v1.0.1-beta/pepgenome-1.0.1-SNAPSHOT-bin.zip
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  run:
    - openjdk  >=6
    - python

test:
  commands:
    - (pepgenome 2>&1 | grep -qF 'PepGenome' || (pepgenome && false))

about:
  home: https://github.com/bigbio/pgatk/
  license: Apache-2.0
  license_family: Apache
  summary: A java tool to map peptide and peptidoform evideces to ENSEMBL Genome Coordinates

extra:
  notes: |-
    PepGenome is Java program that comes with a custom wrapper shell script.
    This shell wrapper is called "opsin" and is on $PATH by default. By default
    "-Xms512m -Xmx1g" is set in the wrapper. If you want to overwrite it you can
    specify these values directly after your binaries. If you have _JAVA_OPTIONS
    set globally this will take precedence.
    For example run it with "PepGenome -Xms512m -Xmx1g"
