{% set name = "neurodocker" %}
{% set version = "0.6.0" %}
{% set sha256 = "ec03aa8543a6a58ed8fcabb855864a553c027da9082fb016075ea8731cab0c68" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/kaczmarj/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python >3.4
    - pip
    - jinja2 >=2.0
    - pyyaml >=3.0
  run:
    - python >3.4
    - jinja2 >=2.0
    - pyyaml >=3.0

test:
  commands:
    - neurodocker --help

about:
  home: https://github.com/kaczmarj/neurodocker
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Neurodocker is a command-line program that generates custom Dockerfiles and Singularity recipes for neuroimaging and minifies existing containers."
