package:
  name: pyasp
  version: "1.4.4"

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv
  number: 0

source:
  url: https://files.pythonhosted.org/packages/ee/fe/dfa8fd74bdbfbd9539bcaa5f7a2aa6f2408eeee3cb2c8629c312e4733a69/pyasp-1.4.4.tar.gz
  sha256: f5525c73353c0e264497795d86ea4db80fd32cd51b7da965f70c46da56b85d37

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pyasp
    - pyasp.ply

about:
  summary: A convenience wrapper for the ASP tools gringo, gringo4 and clasp.
  home: http://pypi.python.org/pypi/pyasp/
  license: GPLv3+
  date: 2017-10-10
