package:
  name: avro-python3
  version: "1.9.1"

source:
  url: https://files.pythonhosted.org/packages/76/b2/98a736a31213d3e281a62bcae5572cf297d2546bc429accf36f9ee1604bf/avro-python3-1.9.1.tar.gz
  sha256: daab2cea71b942a1eb57d700d4a729e9d6cd93284d4dd4d65a378b9f958aa0d2

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3
    - setuptools
  run:
    - python >=3

test:
  imports:
    - avro

about:
  home: http://avro.apache.org/
  license: Apache License 2.0
  summary: 'Avro is a serialization and RPC framework.'
