# Called avro-python2 to avoid conflicts with avro package from conda-forge
# which does not have python bindings included
package:
  name: avro-python2
  version: "1.9.1"

source:
  url: https://files.pythonhosted.org/packages/a1/9a/a2c83f6105d975ec6680b2cab79b4e3bd51ae33f31c10debe8d2485c8f80/avro-1.9.1.tar.gz
  sha256: 9fc06bf0b91877b1b6afac8ad35d66d2e545be2b9b2820e5fba4e35b767bfb9a
build:
  noarch: python
  number: 0
  skip: False

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - avro

about:
  home: http://avro.apache.org/
  license: Apache License 2.0
  summary: 'Avro is a serialization and RPC framework.'
