{% set version = "0.9.9.9" %}
{% set sha256 = "721eeec861b1d5ad8845f04874bdc4f70e21fd2178182cbc9fb591e9886fc6c0" %}

package:
  name: mapcaller
  version: {{ version }}

source:
  url: https://github.com/hsinnan75/MapCaller/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - src_makefile_flags.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - bzip2
    - boost
    - xz
  run:
    - bzip2
    - boost
    - xz

test:
  commands:
    - MapCaller 
    - bwt_index

about:
  home: https://github.com/hsinnan75/MapCaller
  license: MIT
  license_file: LICENSE
  summary: "MapCaller: combined short-read mapper and variant caller"
  description: "An efficient and versatile approach for short-read mapping and variant identification using high-throughput sequenced data."

extra:
  identifiers:
    - doi:10.1101/783605 
