package:
  name: pyx
  version: "0.15"

source:
  url: https://files.pythonhosted.org/packages/f7/25/59c136568c1b61ee087155c874fcd9f7196a943a6a5ee3429efeb30ea2a8/PyX-0.15.tar.gz
  sha256: 0fc3b00c5e7fb6f4aefbf63b95f624297dde47700a82b8b5ad6ebb346b5e4977

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3

test:
  imports:
    - pyx
    - pyx.dvi
    - pyx.font
    - pyx.graph
    - pyx.graph.axis
    - pyx.metapost

about:
  home: http://pyx.sourceforge.net/
  license: GNU General Public License (GPL)
  summary: 'Python package for the generation of PostScript, PDF, and SVG files'
