{% set name = "perl-archive-zip" %}
{% set version = "1.67" %}
{% set sha256 = "be2274344c7659bf9189838dc6b9a59ec6f957c74ddfd35ff2780d56f4592774" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/P/PH/PHRED/Archive-Zip-1.67.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
    - perl-file-path
    - perl-extutils-makemaker
    - perl-time-local
    - perl-test-mockmodule
    - perl-compress-raw-zlib
    - perl-file-temp

  run:
    - perl
    - perl-file-path
    - perl-compress-raw-zlib
    - perl-time-local
    - perl-file-temp

test:
  imports:
    - Archive::Zip
    - Archive::Zip::Archive
    - Archive::Zip::BufferedFileHandle
    - Archive::Zip::DirectoryMember
    - Archive::Zip::FileMember
    - Archive::Zip::Member
    - Archive::Zip::MemberRead
    - Archive::Zip::MockFileHandle
    - Archive::Zip::NewFileMember
    - Archive::Zip::StringMember
    - Archive::Zip::Tree
    - Archive::Zip::ZipFileMember

about:
  home: http://metacpan.org/pod/Archive::Zip
  license: perl_5
  summary: 'Provide an interface to ZIP archive files.'
