package:
  name: menetools
  version: "2.0.1"

source:
  url: https://files.pythonhosted.org/packages/3a/2b/716e38c2dcae5242b4459bf838328437cc6c74315d813eed1611affbc7f2/MeneTools-2.0.1.tar.gz
  sha256: 35b689598397f48ae1ab600b05b0358d8a45cd3cc74b18c65c9c4433dede5830

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - pyasp >=1.4.3

test:
  commands:
    - menecheck.py --help
    - menescope.py --help
    - menepath.py --help
    - menecof.py --help

about:
  home: https://github.com/cfrioux/MeneTools
  license: GPLv3+
  date: 2017-10-13
  summary: Python 3 Metabolic Network Topology Tools
