{% set name = "perl-datetime-format-strptime" %}
{% set version = "1.76" %}
{% set sha256 = "593c26466ed7a3d2cefe9215f1619666c5116bd3a551e0aa74b64a6353fcb50d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-Format-Strptime-1.76.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
    - perl-test-fatal
    - perl-lib
    - perl-exporter
    - perl-params-validationcompiler
    - perl-datetime-timezone
    - perl-parent
    - perl-specio
    - perl-test-warnings
    - perl-package-deprecationmanager
    - perl-carp
    - perl-datetime
    - perl-constant
    - perl-extutils-makemaker
    - perl-try-tiny
    - perl-datetime-locale >=1.05

  run:
    - perl
    - perl-exporter
    - perl-params-validationcompiler
    - perl-parent
    - perl-datetime-locale >=1.05
    - perl-specio
    - perl-package-deprecationmanager
    - perl-carp
    - perl-datetime
    - perl-constant
    - perl-try-tiny
    - perl-datetime-timezone

test:
  imports:
    - DateTime::Format::Strptime
    - DateTime::Format::Strptime::Types

about:
  home: http://metacpan.org/release/DateTime-Format-Strptime
  license: artistic_2
  summary: 'Parse and format strp and strf time patterns'

