package:
  name: perl-xml-libxml
  version: "2.0201"

source:
  url: https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-LibXML-2.0201.tar.gz
  sha256: e008700732502b3f1f0890696ec6e2dc70abf526cd710efd9ab7675cae199bc2

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl
    - perl-xml-sax
    - perl-xml-namespacesupport
    - libxml2
  run:
    - perl
    - perl-xml-sax
    - perl-xml-namespacesupport

test:
  # Perl 'use' tests
  imports:
    - XML::LibXML
    - XML::LibXML::AttributeHash
    - XML::LibXML::Boolean
    - XML::LibXML::Common
    - XML::LibXML::Devel
    - XML::LibXML::ErrNo
    - XML::LibXML::Error
    - XML::LibXML::Literal
    - XML::LibXML::NodeList
    - XML::LibXML::Number
    - XML::LibXML::Reader
    - XML::LibXML::SAX
    - XML::LibXML::SAX::Builder
    - XML::LibXML::SAX::Generator
    - XML::LibXML::SAX::Parser
    - XML::LibXML::XPathContext

about:
  home: https://bitbucket.org/shlomif/perl-xml-libxml
  license: Perl
  summary: 'Interface to Gnome libxml2 xml parsing and DOM library'
