package:
  name: perl-dbd-pg
  version: 3.9.0

source:
  url: https://cpan.metacpan.org/authors/id/T/TU/TURNSTEP/DBD-Pg-3.9.0.tar.gz
  sha256: 3dfdf336c8afa0d839fd99bdb6ffeae6b7e37ae96017287428d22cfa31c5a7df

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl
    - perl-dbi
    - postgresql

  run:
    - perl
    - perl-dbi
    - postgresql

test:
  imports:
    - DBD::Pg

about:
  home: http://search.cpan.org/dist/DBD-Pg/
  license: perl_5
  summary: PostgreSQL database driver for the DBI module
