package:
  name: perl-dbd-pg
  version: 3.10.0

source:
  url: https://cpan.metacpan.org/authors/id/T/TU/TURNSTEP/DBD-Pg-3.10.0.tar.gz
  sha256: e103268a63e2828e3d43659bdba5f743446cbbe047a766f843112eedae105f80

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl
    - perl-dbi
    - postgresql

  run:
    - perl
    - perl-dbi
    - postgresql

test:
  imports:
    - DBD::Pg

about:
  home: http://search.cpan.org/dist/DBD-Pg/
  license: perl_5
  summary: PostgreSQL database driver for the DBI module
