package:
  name: perl-dbd-pg
  version: 3.9.1

source:
  url: https://cpan.metacpan.org/authors/id/T/TU/TURNSTEP/DBD-Pg-3.9.1.tar.gz
  sha256: 7c9eb4ab9b73aecaae8bb8c8a35e79f16f8ec2255a7949c0078a8f6404e28355

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl
    - perl-dbi
    - postgresql

  run:
    - perl
    - perl-dbi
    - postgresql

test:
  imports:
    - DBD::Pg

about:
  home: http://search.cpan.org/dist/DBD-Pg/
  license: perl_5
  summary: PostgreSQL database driver for the DBI module
