package:
  name: ephemeris
  version: "0.10.3"

source:
  url: https://files.pythonhosted.org/packages/d3/52/75e156f22ec7d7a42528af9f951c8a76349977f5d2a04d8199cffd847235/ephemeris-0.10.3.tar.gz
  sha256: b794486676881a49797be70d52ac8a082fd6b79397bf9865bf598dd32e2289fb

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  entry_points:
    - get-tool-list=ephemeris.get_tool_list_from_galaxy:main
    - shed-tools=ephemeris.shed_tools:main
    - workflow-install=ephemeris.workflow_install:main
    - run-data-managers=ephemeris.run_data_managers:main
    - workflow-to-tools=ephemeris.generate_tool_list_from_ga_workflow_files:main
    - setup-data-libraries=ephemeris.setup_data_libraries:main
    - galaxy-wait=ephemeris.sleep:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyyaml
    - galaxy-lib
    - bioblend
    - jinja2
    - galaxy-tool-util >=19.9.0.dev5

test:
  imports:
    - ephemeris

  commands:
    - get-tool-list --help
    - shed-tools --help
    - workflow-install --help
    - run-data-managers --help
    - workflow-to-tools --help
    - setup-data-libraries --help
    - galaxy-wait --help

about:
  home: https://github.com/galaxyproject/ephemeris
  license: Academic Free License (AFL)
  summary: 'Ephemeris is an opinionated library and set of scripts for managing the bootstrapping of Galaxy project plugins - tools, index data, and workflows.'
  license_family: OTHER
