package:
  name: wtforms-components
  version: "0.10.4"

source:
  url: https://files.pythonhosted.org/packages/22/19/7075cb32afc09962f8871bacc55214040dae06f0a7870033f7ceba0a9490/WTForms-Components-0.10.4.tar.gz
  sha256: 4a7751fc12dc4e4b2ef5700973296b5368094dcdf85c2808d2faff2c8e8f4caa
  patches:
    - setup.py.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - wtforms >=1.0.4
    - six >=1.4.1
    - validators >=0.5.0
    - intervals >=0.6.0
    - phonenumbers

test:
  imports:
    - wtforms_components
    - wtforms_components.fields

about:
  home: https://github.com/kvesteri/wtforms-components
  license: BSD License
  summary: 'Additional fields, validators and widgets for WTForms.'
