package:
  name: perl-text-format
  version: "0.61"

source:
  url: https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/Text-Format-0.61.tar.gz
  sha256: bb8a3b8ff515c85101baf553a769337f944a05cde81f111ae78aff416bf4ae2b

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
    - perl-module-build
  run:
    - perl

test:
  imports:
    - Text::Format

about:
  home: http://www.shlomifish.org/open-source/projects/Text-Format/
  license: perl_5
  summary: 'Format text'
