{% set name = "perl-html-form" %}
{% set version = "6.05" %}
{% set sha256 = "36c6c601ca829719f6651be1b80872028f82bec1712608dd860deeb67da32492" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTML-Form-6.05.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
    - perl-cpan-meta-yaml
    - perl-extutils-parsexs
    - perl-data-dumper
    - perl-extutils-cbuilder
    - perl-file-temp
    - perl-text-abbrev
    - perl-text-parsewords
    - perl-cpan-meta
    - perl-version
    - perl-module-metadata
    - perl-extutils-manifest
    - perl-file-path
    - perl-perl-ostype
    - perl-getopt-long
    - perl-html-parser
    - perl-http-message
    - perl-uri

  run:
    - perl
    - perl-text-parsewords
    - perl-cpan-meta
    - perl-version
    - perl-extutils-parsexs
    - perl-data-dumper
    - perl-module-metadata
    - perl-extutils-cbuilder
    - perl-extutils-manifest
    - perl-file-path
    - perl-perl-ostype
    - perl-text-abbrev
    - perl-getopt-long
    - perl-html-parser
    - perl-http-message
    - perl-uri
    
test:
  # Perl 'use' tests
  imports:
    - HTML::Form

about:
  home: https://metacpan.org/pod/HTML::Form
  license: perl_5
  summary: Class that represents an HTML form element
