package:
  name: bitstring
  version: "3.1.6"

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

source:
  url: https://files.pythonhosted.org/packages/f4/87/fe6f7093088f4396e84c1b5d5dfb08c4840487ad46ff4805b7008c8f5ffc/bitstring-3.1.6.tar.gz
  sha256: c97a8e2a136e99b523b27da420736ae5cb68f83519d633794a6a11192f69f8bf

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - bitstring

about:
  home: https://github.com/scott-griffiths/bitstring
  license: MIT License
  summary: 'Simple construction, analysis and modification of binary data.'
  license_family: MIT
